In [2]:
import pandas as pd
# Read in data from dataset
dataset = "../../datasets/quora_duplicate_questions.tsv"
data = pd.read_csv(dataset,sep='\t')

In [3]:
data[0:10]

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
5,5,11,12,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",1
6,6,13,14,Should I buy tiago?,What keeps childern active and far from phone ...,0
7,7,15,16,How can I be a good geologist?,What should I do to be a great geologist?,1
8,8,17,18,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",0
9,9,19,20,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,0

In [4]:
import csv
import pandas as pd

# Read in GloVe word embeddings
embeddings_50d = "../../word_embeddings/glove.6B/glove.6B.100d.text"
embeddings_100d = "../../word_embeddings/glove.6B/glove.6B.100d.text"
embeddings_200d = "../../word_embeddings/glove.6B/glove.6B.200d.text"
embeddings_300d = "../../word_embeddings/glove.6B/glove.6B.300d.txt"

# Must change embedding_dim when you change the word embedding selection
embeddings = pd.read_table(embeddings_300d, delim_whitespace=True,
                           index_col=0, header=None, quoting=csv.QUOTE_NONE)
embedding_dim = 300

In [6]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import text_to_word_sequence

ws = [str(word) for word in embeddings.axes[0]]

def process_sentence(sentence):
    word_sequence = text_to_word_sequence(str(sentence))
    return [ws.index(word) if word in ws else 0 for word in word_sequence]

q1s = [process_sentence(sentence) for sentence in data["question1"]]
q2s = [process_sentence(sentence) for sentence in data["question2"]]

df = pd.DataFrame({
    "question1" : q1s,
    "question2" : q2s,
    "labels" : data["is_duplicate"]
})

In [7]:
df

,question1,question2,labels
0,"[102, 14, 0, 1065, 21, 1065, 3372, 4, 4280, 6,...","[102, 14, 0, 1065, 21, 1065, 3372, 4, 4280, 6,...",0
1,"[102, 14, 0, 523, 3, 180152, 8849, 41, 16359, ...","[102, 54, 1927, 83, 0, 792, 78, 8396, 0, 18015...",0
2,"[197, 86, 41, 686, 0, 1512, 3, 192, 925, 2540,...","[197, 86, 925, 1512, 30, 1041, 21, 20463, 131,...",0
3,"[738, 913, 41, 7278, 191, 10678, 197, 86, 41, ...","[596, 0, 6345, 61, 7460, 1021, 795, 7460, 14, ...",0
4,"[42, 48, 13151, 6, 430, 0, 3191, 2982, 16904, ...","[42, 2120, 54, 3981, 6, 2982, 430]",0
5,"[29593, 41, 913, 7, 51980, 1662, 3539, 3377, 5...","[0, 7, 4026, 51980, 1662, 3377, 5, 56141, 6, 5...",1
6,"[189, 41, 987, 44842]","[102, 4215, 0, 1546, 5, 372, 25, 1264, 5, 974,...",0
7,"[197, 86, 41, 30, 7, 219, 21010]","[102, 189, 41, 88, 4, 30, 7, 353, 21010]",1
8,"[61, 88, 81, 234, 0, 773, 3, 0]","[61, 88, 81, 234, 773, 3, 5]",0
9,"[10469, 128, 86, 41, 22048, 192, 3812, 0, 0]","[197, 88, 41, 22048, 10469, 0, 10, 415, 925]",0
10,"[3241, 4, 596, 6654, 3, 46029, 622, 61265, 0]","[102, 32, 77, 3, 0, 654, 11440, 86, 1361, 59, ...",0
11,"[197, 88, 41, 1465, 5, 596, 192, 8364, 1939]","[197, 86, 41, 253, 64, 192, 8364, 1939]",1
12,"[102, 86, 159, 5787, 1673, 4, 2368]","[197, 86, 81, 159, 5787, 1673, 4, 2368]",1
13,"[102, 15, 392, 58, 2221, 1221, 117]","[102, 15, 392, 58, 2221, 1221]",1
14,"[102, 32, 0, 1487, 4, 511, 392, 1416, 25, 7, 1...","[102, 32, 0, 1487, 4, 511, 392, 1416, 25, 7, 1...",0
15,"[102, 54, 7, 10468, 2523, 1702, 10, 533, 146, ...","[197, 43, 7, 10468, 2523, 3194, 0, 543, 11682,...",1
16,"[102, 260, 12532, 1702]","[102, 260, 12532, 889]",1
17,"[738, 88, 1946, 303, 4, 30, 1095, 17, 0, 1856,...","[197, 88, 2284, 998, 49, 9726, 7, 1749]",0
18,"[738, 32, 100, 109, 309001, 2589, 7743, 1208, ...","[738, 88, 69, 1712, 309001, 1208, 42, 86, 30, ...",1
19,"[42, 14, 0, 254, 2150, 2253, 3374, 6, 230380]","[42, 14, 0, 254, 2150, 2253, 1064, 6, 22298]",0
20,"[738, 88, 3905, 662, 298]","[738, 32, 3905, 5, 24744, 4605, 298]",1
21,"[0, 2865, 1318, 4, 30, 17095]","[102, 86, 41, 88, 4, 1566, 134, 17095, 3, 1318]",0
22,"[102, 32, 0, 1208, 189, 36, 1712, 13, 309001]","[42, 995, 189, 41, 1712, 13, 309001]",0
23,"[197, 181, 14, 407, 34012, 6, 8316]","[111, 86, 41, 596, 7, 6249, 3099, 10, 13307, 4...",0
24,"[102, 260, 20, 1702, 12, 359, 79, 41, 662, 22,...","[197, 109, 246, 7, 122, 88, 7, 0, 1281, 16539]",0
25,"[102, 32, 77, 7080, 13, 433, 20, 131, 0, 664, ...","[102, 32, 77, 7080, 13, 433, 20, 131, 0, 664, ...",0
26,"[102, 14, 1170, 3250]","[102, 14, 0, 1170, 3250, 4431]",0
27,"[260, 908, 241, 317, 181, 2604, 13, 884]","[197, 88, 884, 4228, 4, 0, 908]",0
28,"[102, 14, 254, 179, 4, 159, 308, 1292]","[102, 14, 254, 179, 4, 1712, 10, 308, 1292]",0
29,"[197, 189, 41, 3298, 10, 855, 294, 264]","[197, 48, 189, 346, 12, 18, 67, 2215, 3298, 10...",1
...,...,...,...
404260,"[42, 1264, 14, 254, 124, 141996]","[102, 14, 0, 254, 1264, 4, 987, 1268, 71702]",0
404261,"[38, 14, 0, 1250, 96, 814, 186, 3, 53171, 1395]","[38, 14, 0, 96, 814, 1395, 6, 0, 186, 3, 53171...",1
404262,"[197, 88, 81, 124827, 7, 15158, 10819]","[197, 88, 41, 22634, 7, 15158, 10819]",0
404263,"[197, 260, 0, 4471, 3, 9044, 9542, 4228, 4, 70...","[738, 260, 18306, 4228, 56, 4, 701, 4914, 73, ...",0
404264,"[14, 20, 1876, 4, 1612, 29, 3751, 5747, 268, 2...","[197, 88, 41, 159, 7, 1876, 5, 5115, 268, 231]",0
404265,"[197, 86, 41, 1885, 2555, 13, 192, 719]","[102, 189, 41, 3623, 4, 1885, 2555]",1
404266,"[102, 14, 0, 989, 9500, 182, 4, 0, 1264, 7883,...","[192, 8254, 210, 18, 16201, 26, 8320, 14005, 1...",0
404267,"[102, 32, 0, 3158, 3, 0, 807, 3, 0, 1956, 2552]","[102, 35, 0, 96, 481, 3158, 5, 2115, 3, 0, 807...",1
404268,"[738, 0, 53, 149, 88, 353, 403, 117, 6, 0, 0, ...","[189, 41, 1474, 192, 461, 964, 13, 0, 403]",0
404269,"[197, 88, 81, 26033, 52170, 4941, 6638]","[102, 260, 20, 998, 117, 4, 33, 52170, 4941, 6...",0
404270,"[102, 14, 0, 2333, 118, 38, 5, 197]","[102, 14, 0, 2333, 118, 5, 5]",0
404271,"[260, 11208, 33, 130, 7919, 12, 32, 149, 2977,...","[102, 15, 1969, 0, 422, 62, 394, 197, 119, 39,...",0
404272,"[102, 32, 0, 254, 50, 569, 909, 46, 19516, 12,...","[102, 32, 77, 1676, 9335, 1634, 4315, 12, 3604...",1
404273,"[102, 3371, 83, 81, 339, 4177, 6, 7, 3424, 2737]","[102, 54, 1927, 83, 41, 339, 4177, 773, 3, 430...",1
404274,"[43, 0, 182, 2064, 3, 19521, 511, 46, 1087, 0,...","[102, 921, 3, 1108, 43, 0, 182, 2064, 33]",1
404275,"[6, 3567, 738, 88, 53, 23178, 4902, 5, 1164, 3...","[102, 14, 7, 6659, 5740, 6, 3567, 197, 88, 81,...",0
404276,"[102, 14, 0, 10108]","[102, 14, 0, 10108]",0
404277,"[102, 260, 28691, 88]","[102, 32, 16767, 69, 117]",0
404278,"[197, 119, 81, 3298, 10, 115365, 52708, 0]","[197, 119, 81, 3298, 10, 0, 115365, 104243, 42...",0
404279,"[102, 14, 0, 3311, 79, 1386, 4, 1190, 7, 41300...","[102, 14, 7, 6233, 5, 12606, 179, 4, 1190, 29,...",0
404280,"[102, 32, 77, 9362, 2720, 4, 3433, 4, 7, 47179...","[102, 32, 77, 9362, 2720, 3433, 4, 7, 47179, 1...",1
404281,"[738, 14, 0, 33464, 6, 25253, 10982, 5, 0, 261...","[738, 14, 0, 17249, 6, 36687, 10982, 5, 0, 261...",1
404282,"[197, 260, 7, 173, 2296, 1483, 161]","[197, 32, 173, 2296, 4922, 3128]",1
404283,"[102, 88, 81, 269, 3, 0, 5839, 3, 0, 0, 22156,...","[102, 43, 0, 23054, 6837, 4, 0, 15463, 3292, 6...",0
404284,"[102, 260, 51855, 203, 59, 11181]","[102, 260, 51855, 203, 59, 11324, 5, 11181]",1
404285,"[197, 109, 44333, 32, 63, 6, 0, 17676, 3874, 1...","[197, 109, 44333, 32, 63, 6, 40172, 3874, 1032...",0
404286,"[88, 81, 733, 63, 14, 214, 49, 336]","[14, 20, 1446, 12, 63, 14, 214, 49, 336]",1
404287,"[102, 14, 48, 9569]","[0, 37, 9569]",0
404288,"[102, 14, 0, 28886, 940, 772, 3, 756, 110, 437...","[41, 913, 518, 333, 0, 747, 34, 41, 303, 4, 23...",0
404289,"[102, 14, 117, 4, 33, 1739, 17, 5591]","[102, 14, 20, 117, 4, 33, 1739, 17, 392, 5591]",0

In [23]:
max_question_length = max(max([len(str(question)) for question in df.question1],[len(str(question)) for question in df.question2]))
print(f"Max length: {max_question_length}")

15
15
15
13
16
20
5
8
9
13

[None, None, None, None, None, None, None, None, None, None]

In [ ]:
from sklearn.model_selection import train_test_split
import itertools

validation_set_size = round(0.10*len(df))
training_set_size = len(df) - validation_set_size

X = df[["question1","question2"]]
Y = df["labels"]

X_train,X_validation,Y_train,Y_validation = train_test_split(X,Y,test_size=validation_set_size)

X_train = {
    'left': X_train.question1, 
    'right': X_train.question2
}
X_validation = {
    'left': X_validation.question1, 
    'right': X_validation.question2
}
Y_train = Y_train.values
Y_validation = Y_validation.values

for dataset, side in itertools.product([X_train, X_validation], ['left', 'right']):
    dataset[side] = pad_sequences(dataset[side],  maxlen=max_question_length)

In [ ]:
from keras.layers import Input, Dense, Embedding, LSTM, Lambda
from keras.models import Model
import keras.backend as K

def exponent_neg_manhattan_distance(left, right):
    return K.exp(-K.sum(K.abs(left-right), axis=1, keepdims=True))

n_hidden_units = 32;

left_input = Input(shape=(max_question_length,), dtype='int32')
right_input = Input(shape=(max_question_length,), dtype='int32')

embedding_layer = Embedding(len(embeddings), embedding_dim, input_length=max_question_length)
embedded_left = embedding_layer(left_input)
embedded_right = embedding_layer(right_input)

lstm = LSTM(n_hidden_units)

left_out = lstm(embedded_left)
right_out = lstm(embedded_right)

similarity_function = Lambda(function=lambda x: exponent_neg_manhattan_distance(x[0], x[1]),output_shape=lambda x: (x[0][0], 1))([left_out, right_out])

model = Model(inputs=[left_input, right_input], outputs=[similarity_function])

In [ ]:
from keras.optimizers import Adadelta
from time import time
import datetime
import tensorflow as tf

batch_size = 64
num_epoch = 10

model.compile(
    loss='mean_squared_error',
    optimizer=tf.train.GradientDescentOptimizer(0.5),
    metrics=['accuracy'])

start_time = time()
trained = model.fit(
    [X_train['left'], X_train['right']],
    Y_train,
    batch_size=batch_size,
    epochs=n_epoch,
    validation_data=([X_validation['left'], X_validation['right']],
                     Y_validation))
print(
    f"Training time finished. {num_epoch} epochs in {datetime.timedelta(seconds=time() - start_time)}."
)

In [ ]:
model.save("semantic-similarity-v1")